apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/component: app

configMapGenerator:
- name: tc-agent-config
  files:
  - application.yaml

resources:
- svc.yml
- depl.yml
- ing.yml
