apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpas
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector: { }
  template:
    metadata:
      labels:
        app.life.uni-leipzig.de/redundancy: none
        app.life.uni-leipzig.de/service-level: silver
    spec:
      enableServiceLinks: false
      initContainers:
      - name: import-ca-certs
        image: eclipse-temurin:21-jdk
        env:
        - name: USE_SYSTEM_CA_CERTS
          value: "true"
        args: [ "sh", "-c", "cp ${JRE_CACERTS_PATH:-/opt/java/openjdk/lib/security/cacerts} /cacerts/cacerts" ]
        volumeMounts:
        - name: ca-certs
          mountPath: /certificates
          readOnly: true
        - name: cacerts
          mountPath: /cacerts
      containers:
      - name: gpas
        image: mosaicgreifswald/gpas:2025.2.0@sha256:e61946ae994e658ecdeb5dfc86b4102d248e22cfdde10b6c6e6dfefeb654739c
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: TTP_GPAS_DB_HOST
          value: "gpas-db"
        - name: TTP_GRAS_DB_HOST
          value: "gpas-db"
        - name: TTP_NOTI_DB_HOST
          value: "gpas-db"
        - name: TTP_GPAS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: gpas-db-credentials
              key: password
        - name: TTP_GRAS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: gpas-db-credentials
              key: password
        - name: TTP_NOTI_DB_PASS
          valueFrom:
            secretKeyRef:
              name: gpas-db-credentials
              key: password
        - name: WF_NO_ADMIN
          value: "true"
        - name: MOS_INCLUDE_PROCESSES
          value: "wildfly"
        - name: TTP_KEYCLOAK_REALM
          value: "distance-xt"
        - name: TTP_KEYCLOAK_SERVER_URL
          value: "https://auth.distance-xt.life.uni-leipzig.local"
        - name: TTP_KEYCLOAK_SSL_REQUIRED
          value: "external"
        - name: TTP_KEYCLOAK_CONFIDENTIAL_PORT
          value: "443"
        - name: TTP_WEB_KEYCLOAK_CLIENT_ID
          value: "trust-center-web"
        - name: TTP_WEB_KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-credentials
              key: web-client-secret
        - name: TTP_FHIR_KEYCLOAK_CLIENT_ID
          value: "trust-center-fhir"
        - name: TTP_FHIR_KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-credentials
              key: fhir-client-secret
        - name: TTP_GPAS_WEB_AUTH_MODE
          value: "keycloak"
        - name: TTP_FHIR_KEYCLOAK_ENABLE
          value: "true"
        - name: TTP_GPAS_AUTH_DOMAIN_ROLES
          value: "FORCED"
        startupProbe:
          httpGet: &probe
            path: /
            port: http
          failureThreshold: 24
          periodSeconds: 10
        readinessProbe:
          httpGet: *probe
        livenessProbe:
          httpGet: *probe
        resources:
          requests:
            cpu: "125m"
            memory: "2.5Gi"
          limits:
            memory: "2.5Gi"
        volumeMounts:
        - name: cacerts
          mountPath: /usr/lib/jvm/zulu21/lib/security/cacerts
          subPath: cacerts
          readOnly: true
        - name: wildfly-cli
          mountPath: /entrypoint-wildfly-cli/proxy-forwarding.cli
          subPath: proxy-forwarding.cli
          readOnly: true
      volumes:
      - name: ca-certs
        configMap:
          name: life-ca-certs
          items:
          - key: life-root-ca-2.pem
            path: life-root-ca-2.crt
      - name: cacerts
        emptyDir: { }
      - name: wildfly-cli
        configMap:
          name: wildfly-cli
